apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  APP_HOST: 0.0.0.0
  APP_PORT: '8080'
  BACKEND: app
  BACKEND_PORT: '8080'
  CELERY_ACCEPT_CONTENT: '["application/json"]'
  CELERY_BROKER_URL: amqp://test:test@rabbitmq.rabbitmq.svc.cluster.local:5672//
  CELERY_MAIN_QUEUE: main-queue
  CELERY_TASK_SERIALIZER: json
  CELERY_TASK_TRACK_STARTED: 'True'
  CREATE_TASKS: 'True'
  EMAILS_ENABLED: 'True'
  EMAILS_FROM_EMAIL: testapitextstats@gmail.com
  EMAILS_FROM_NAME: TextStat
  ENV: staging
  FILE_CONTENT_TYPES: '["text/plain"]'
  FIRST_SUPERUSER: user@test.com
  FIRST_SUPERUSER_PASSWORD: Qweqwe123.
  HOST: _
  LOG_LEVEL: INFO
  NGINX_PORT: '80'
  PORT: '8080'
  POSTGRES_DATA: /var/lib/postgresql/data
  POSTGRES_DB: test
  POSTGRES_HOSTNAME: postgresql.postgresql.svc.cluster.local
  POSTGRES_PASSWORD: test
  POSTGRES_PORT: '5432'
  POSTGRES_SERVER: postgresql.postgresql.svc.cluster.local
  POSTGRES_USER: test
  PROJECT_NAME: '"API TextStat"'
  PROJECT_PATH: /var/app
  RABBITMQ_PORT: '5672'
  ROOT: /var/app
  SERVER_HOST: http://localhost/docs
  SERVICE_CELERY_IMAGE: textstat_celery
  SERVICE_IMAGE: textstat
  SMTP_HOST: smtp.elasticemail.com
  SMTP_PASSWORD: E02AFC763CFAA24211968BC99FB86F1AE525
  SMTP_PORT: '587'
  SMTP_TLS: 'True'
  SMTP_USER: testapitextstats@gmail.com
  SSL: 'False'
  SSL_CERTIFICATE: fullchain1.pem
  SSL_CERTIFICATE_KEY: privkey1.pem
  SSL_DHPARAM: dhparams.pem
  SSL_KEYS_LOCAL_PATH: /etc/letsencrypt/archive/dev.azscore.pw
  SSL_KEYS_PATH: /var/app/ssl_cert
  SSL_PORT: '443'
  USERS_OPEN_REGISTRATION: 'False'
