apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: bakavets/demo-dsd:0.2
        command:
        - /bin/sh
        - /var/app/scripts/celery.sh
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: app-env
        volumeMounts:
        - mountPath: /var/app/files
          name: celery-volume
      volumes:
      - name: celery-volume
        persistentVolumeClaim:
          claimName: app-pvc

